### PR TITLE
Feature/tao 3496 refactor component

### PR DESCRIPTION
**Pull request by jsconan**
Related to: https://oat-sa.atlassian.net/browse/TAO-3496

Requires:
- https://github.com/oat-sa/extension-tao-proctoring/pull/295
- https://github.com/oat-sa/tao-core/pull/1203 :ok:
- https://github.com/oat-sa/tao-core/pull/1204 :ok:
- https://github.com/oat-sa/tao-core/pull/1205 :ok:
- https://github.com/oat-sa/tao-core/pull/1206 :ok:
- https://github.com/oat-sa/tao-core/pull/1207 :ok:
- https://github.com/oat-sa/tao-core/pull/1218 :ok:
- https://github.com/oat-sa/extension-tao-lti/pull/50 :ok:

Update the monitor page to be compatible with new proctoring client.
For more information, please refer to the [proctoring PR](https://github.com/oat-sa/extension-tao-proctoring/pull/295)

### CODE REVIEW

**Comment by jsconan** [comment]
@antoinerobin Please review the PHP code.
@krampstudio will be the final reviewer.

**Comment by jsconan** [comment]
Will need some adjustments regarding the config of branding (showControls).
However the PR could be merged as it, the changes could be provided in another PR.

**Comment by jsconan** [comment]
I made the adjustments regarding the config of the branding (showControls).

**Comment by krampstudio** [comment]
Looks ok, I'm going to merge it

**Pull request merged**
